### ISSUE TITLE
Add android 6-8 to the table

### ISSUE THREAD

**Issue by mlucool** [compat-table/compat-table#1089]
Android 6/7 common and 8 is coming ([see here](https://en.wikipedia.org/wiki/Android_version_history). Can it be added to https://kangax.github.io/compat-table/es6/?

**Comment by afmenez** [comment]
There's no Android Browser after Android 4:
http://androidandme.com/2012/02/applications/goodbye-old-browser-chrome-to-become-the-standard-browser-on-android-4-0-and-above/
So maybe the real issue here should be "remove Adroid 4+ from the table".  I don't know where those results come from (Chrome for Android? Samsung Browser?), but they don't seem to be named correctly.

**Comment by mlucool** [comment]
Yeah, it is confusing. I guess something that would be useful is moving android browser to 'obsolete platforms' .

**Comment by afmenez** [comment]
I'll do that once the pull queue moves forward since this would all the patches there.

**Comment by afmenez** [comment]
I believe this can be closed now.
