### ISSUE TITLE
Samsung browser data

### ISSUE THREAD

**Issue by Bilge** [compat-table/compat-table#1247]
It would be nice to have compatibility data for the Samsung browser.

**Comment by afmenez** [comment]
It uses the WebKit engine, do we really need a different entry for every fork?

**Comment by ljharb** [comment]
Only if it’s got different results, I’d think.

**Comment by satyanash** [comment]
It's useful because a lot of people don't update the default browser (SamsungBrowser) and it runs obsolete versions of webkit and you get user agent strings like this:
`... SamsungBrowser/5.4 Chrome/51.0.2704.106 ...`

This could be fixed by allowing `compat-table` to show info for older browser versions.

**Comment by ExE-Boss** [comment]
MDN’s [Browser Compatibility Data](https://github.com/mdn/browser-compat-data) project might help with this, and it’s [available on npm](https://www.npmjs.com/package/mdn-browser-compat-data).
