### ISSUE TITLE
Intl tests fails .. add test to intl output interfaces ... it's not standard at all

### ISSUE THREAD

**Issue by mhf-ir** [compat-table/compat-table#1354]
See this repo for more information all interface of Intl has different outputs:

Repo
https://github.com/mhf-ir/intl-browser-test

Sample diff:
https://github.com/mhf-ir/intl-browser-test/blob/master/diff.md

<table>
  <tr>
    <td colspan="2"><code>new Intl.DateTimeFormat('ar').format(test_date)</code></td>
  </tr>
  <tr>
    <td>Chromium 69 Ubuntu</td>
    <td>1‏/2‏/2018</td>
  </tr>
  <tr>
    <td>Firefox 63 Linux</td>
    <td>١‏/٢‏/٢٠١٨</td>
  </tr>
</table>

**Comment by zbraniecki** [comment]
I don't understand the complaint. Browsers are free to differ in what output they produce out of the Intl API. The whole Intl API follows the "best effort" approach and they try to align the output to the input based on data. Comparing the output between different engines is no different from comparing between different versions of the same engine in case we update the underlying data and complaining that the output changed.

It will change, because data gets updated, and there can be multiple data sources. You should report if the output is *invalid* (so, you asked for `fa-IR`, got `fa-IR` but the values are off), but not if the fallback has been used (you asked for `fa-IR`, and the browser fallbacked on `fa`).

**Comment by ljharb** [comment]
@zbraniecki is there something we should add or fix, or should this be closed?

**Comment by zbraniecki** [comment]
I believe this should be closed.
