### ISSUE TITLE
feature request: add Deno to the table

### ISSUE THREAD

**Issue by tigercosmos** [compat-table/compat-table#1651]
As Deno growing up, it would be nice to have Deno in the table.

**Comment by Jack-Works** [comment]
Deno is based on V8 maybe we can just list the engine 🤔

**Comment by KilianKilmister** [comment]
> Deno is based on V8 maybe we can just list the engine 🤔

@Jack-Works So is *NodeJS* and Chromium browsers like **Edge** and **Opera**, but they interpret the word 'experimental' a bit differently than Google and tend to be a bit behind chrome in terms of features. No idea how up-to-date deno usually is, but i'd argue it should have its own spot.

I mean looking at the current listings for serverside runtimes:
- Echo JS 
  - last activity in the repo was in 2018
- JXA 
  - JavaScript automation for MacOS 
- Kimona xs6
  - last activity in the repo was in 2016
- NodeJS 
  - just adding text here so it looks more uniform
- DuctTape
  - doesn't even suport es2015 Map & Set
- JerryScript
   small footprint for IoT usage
- Nashorn
  - a Java implementation, deprecated since Java 11 & removed with Java 15
- GraalVM
  - ~~which just uses nodejs under the hood~~it actually uses it's own engine but can provide bindings for scripts written for node

Out of these i only know 3 by name: JXA, JerryScript and of course node, and i'm someone who's very interested in JS-engines, and i assume a lot of JS-devs will equally draw a blank on most of those.
If you exlude node, Deno is undesputed "royality" here. It clearly deserves a spot

**Comment by ljharb** [comment]
In what way is Deno "royalty" at all? It's a relatively new JS server engine.

**Comment by KilianKilmister** [comment]
@ljharb i mean by how it's pretty well known by name is in active development and has a decent size userbase

**Comment by ljharb** [comment]
Indeed, as are Duktape and Graal.

**Comment by KilianKilmister** [comment]
@ljharb duktape and JerryScript are rather niche with their integrated/IoT target.

But thinking about it, i might very well be underestimating usage of Graal. It's possible that it's better known outside my field and I was biased by what i see in my field.

But we're getting a bit off track. I'm not trying to delegitimize any of these engines, all I'm trying to say is Deno isn't just some small venture anymore and should certainly be allowed on the list

**Comment by kitsonk** [comment]
> Deno is based on V8 maybe we can just list the engine 🤔

Sadly, there is more than just V8 supporting something to make it compatible in the runtime.  Top-level await is a good example of something that is more than an engine to support, as it has impacts on how the v8 APIs are leveraged.  Another good example is import assertions.  There is quite a lot the implementor has to do in order to support them, even though the v8 parses them out.

While Deno isn't royalty... I wouldn't dismiss it.  If Duktape and Graal are suitable for inclusion, why would Deno not be, royalty or not?

**Comment by Alhadis** [comment]
Deno is now listed in MDN's support tables alongside Node.js.

In other words, it's high-time to "Denote" this repository. If you catch my drift.

**Comment by crowlKats** [comment]
This can be closed since Deno is now on the table.

**Comment by ljharb** [comment]
Indeed, done in #1828.

**Comment by MichaelDeBoey** [comment]
Would you guys also be interested in creating a `deno-compat-table` repo that works just the same as [node-compat-table](https://github.com/compat-table/node-compat-table) and deploys to [deno.green](https://deno.green)?

**Comment by ljharb** [comment]
I think node-compat-table is the place to do that, not here.
