### ISSUE TITLE
Remove es6 tests for `Regexp.prototype.compile` and `String.prototype HTML`

### ISSUE THREAD

**Issue by johnjbarton** [compat-table/compat-table#178]
The es6 tests include two tests which make no sense:  `Regexp.prototype.compile` and `String.prototype HTML`. These are implemented on all the platforms so there is no reason to say they are not implemented by eg traceur and EJS. By that logic all of ES5 would need to be listed and implemented as polyfills.

**Comment by webbedspace** [comment]
The reason I included those tests in my PR is because they are not specified in the ES5 spec, but _are_ specified in the ES6 spec - hence, there are as much a part of ES6 (as distinct from ES5 or ES3) as anything else, albeit in annex B.

I wish to dispute your point that their being implemented on "all the platforms" is self-evident enough that their place on the table is meaningless. (TBH, I didn't know `Regexp.prototype.compile` existed until I found it in the spec, let alone that it was a widespread de facto extension). I think even a solid row of "Yes"es conveys useful information in itself.

But, the point you make about EJS is a good one that has been made before: non-browser environs are free to ignore annex B, so the red "No" is a tad misleading w/r/t spec-compliance. Maybe a different colour should suffice for those results.

Traceur falls under the same purview: while it's marketed for use in browsers, it doesn't _necessarily_ have to run in a browser platform. As a result, it has no particular onus to implement annex B methods. 

(Which suddenly makes me realise: Traceur's "yes" result for `__proto__ in object literals` is a **incorrect**, because all it really does is delegate `__proto__`'s special syntax to the host platform.)

**Comment by johnjbarton** [comment]
All three of the features you discuss work in all browsers and on nodejs. 

Compatibility is a practical question. Users of compat-table are here to learn if features they use are widely available.  Marking these three columns red for traceur and EJS misleads users of compat-table.  

Are there platforms which do not support these features? It is not the goal of Tracuer or EJS to support unusual platforms. Our goal is to support ES6 transition for the large majority of users working on common platforms. Marking these columns red is a disservice to these users.
