### ISSUE TITLE
Support for automatic testing of compatibility

### ISSUE THREAD

**Issue by johnjbarton** [compat-table/compat-table#229]
Over at the traceur project I wrote a program to extract the test code from data-es6.js and apply traceur to the result. We run this test as part of our pre-commit procedure.

The change in PR #209 broke my extractor and the new format seems hard to work with, but perhaps you have a suggestion. It seems like this was a deliberate change to support automatic testing, but now I all see in my code are empty functions because of the `/*  */` comments.

**Comment by webbedspace** [comment]
#209 arose from the discussion in #190. The primary motivation was to save on including try-eval-catch wrappers in every non-trivial ES6 test. (How did Traceur handle those things, might I ask? I believe [this](https://github.com/google/traceur-compiler/blob/25d59d30b364854fb3bd5db8ff52937397bdb93d/test/verify-compat.js) is the script you're using, and while it seems to handle `eval`, it doesn't account for those few times I used `Function(...)()` instead...)

Thinking it over, I guess the issue is that `data-es6`'s tests.exec properties are served as (blank) functions, rather than strings. So, I'll work up a pullreq that converts them to strings of ES6/ES5/non-standard code (which is how `build.js` treats them, anyway) at the end of the script.

**Comment by webbedspace** [comment]
In #234 I've changed it so that a test's .exec property is now converted to a string comprising the function body (just the body, as if ready to pass directly to the `Function` constructor, if you felt like it).

**Comment by johnjbarton** [comment]
Traceur formerly extracted the text inside of the `eval()`, transcoded it, and evaled it inside of try-catch. 

I tried your regexp solution but I am unsuccessful. I added 

``` js
 var fn = test.exec;
      var m = (fn + "").match(/[^]*\/\*([^]*)\*\/\}$/);
      var functionBody = m ? m[1] : "no match";
      console.log(test.name  + ' functionBody ' + functionBody);
```

to my code and it prints 'no match' for all of the tests.  If I print:

``` js
console.log(test.name + ' exec: ' + test.exec);
```

then I get function bodies but no comments.

**Comment by webbedspace** [comment]
I'm not certain but I suspect `System.loadAsScript` might be converting all of `data-es6`'s code directly to Traceur'd ES6 before running it, which in effect wipes all of the comments from the functions. Maybe you could use another method such as `require()` or a standard XHR to load it? (Or you could rewrite Traceur so that output code preserves comments in input code. (Don't actually do that.))

(In what platform are these Traceur tests run? IE 9? A crinkly version of Node guaranteed to only have ES5 features?)

**Comment by johnjbarton** [comment]
oh, duh! Thanks!

Some tests are still problems. I'll open a separate issue for these.
