### ISSUE TITLE
'modules' test is not valid

### ISSUE THREAD

**Issue by johnjbarton** [compat-table/compat-table#240]
``` js
exec: function () {
    export var foo = 1;
    return true;
  }
```

should always result in a syntax error, whether the compiler supports modules or not.  The module keywords are not valid inside of a function.

**Comment by webbedspace** [comment]
Hmm... I feel like the most "authentic" way to test modules would be to put their code in a separate JS file which the test includes... but then, that would prevent various other environments from running the test using just the `data-es6` file...

Would the `export` keyword be valid inside a global `eval()`, I wonder?

**Comment by johnjbarton** [comment]
Maybe this would work: 

``` js
  exec: function() { /*
    code 
*/},
```

where `code` is the complete text for a test, not the body of a function.  Thus tests intended to be functions would have another function inside of the `/*  */`.

Or maybe that was your intent?

**Comment by webbedspace** [comment]
Well, speaking solely of the HTML page for a moment... every test on the page has to be wrapped in roughly the following code, either implicitly (enabled by use of `/**/` "comment strings" in its `exec` function property) or explicitly:

``` javascript
test(function(){try{return Function("...test function body...")()}catch(e){return false;}}());
```

`test()` prints out the HTML for a "Yes"/"No" cell depending on the boolean value of its argument. `Function()()` is necessary because new syntax like `let` or `export` will usually throw on compilation, and this way the syntax error can be thrown at runtime and caught by `try`. (Several legacy tests that do not use new syntax, like most of the ES5 table, don't use or necessarily need this.) `function(){}()` is necessary because `try` can't be used in expression form (i.e. as an argument to `test()`).

So, every test's code is already in the interior of a function. What could be done is to change the `Function()()` into a global `eval` - but this of course can't be done for just every test because then each `var` would become global (and certain tests require an absence of `"use strict"`, which would prevent eval globals, to ensure full conformance).

(...Someone should probably put this entire post in the readme or something.)

**Comment by Vanuan** [comment]
Reopen?
