### ISSUE TITLE
Move the iOS columns between the Safari and WebKit columns

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#252]
WebKit is the development build of the engine used for both Safari and iOS Safari, and represents "the future" of both browsers in the same way that FF34 is "the future" of FF31, and Node Harmony is "the future" of Node. Therefore, the table columns should be arranged like so: SF 6 SF 7, IOS 7, IOS 8, WK.

Yes, I know you may want to segregate these columns by device type, but I think this is a more useful arrangement for understanding what WK's results mean for iOS and SF.

**Comment by webbedspace** [comment]
(And now that I think about it, I guess PH should be moved nearer to WK as well - maybe when it gets updated to PH 2.0. And if Node 0.12 lands, we could move that nearer to Chrome.)

**Comment by kangax** [comment]
The reason I put them separately is because I wanted separation by Mobile and Desktop (and Compilers). This is why all compilers are currently together, then all desktop, and now mobile (I'd like to add Android and others as well at some point). On the other hand, I can see how grouping by engine is sensible as well, so perhaps in the future we can support multiple "views".

**Comment by webbedspace** [comment]
Well, technically we already support 2 "views" (Normal, and Most Implemented) so I expect it wouldn't be too tricky to add a third for JS Engine.
