### ISSUE TITLE
Add 6to5

### ISSUE THREAD

**Issue by UltCombo** [compat-table/compat-table#281]
The [6to5 compiler](https://github.com/sebmck/6to5) has a very nice [ES6 support](https://github.com/sebmck/6to5#comparison-to-other-transpilers). Perhaps add it to the ES6 compat table?

**Comment by webbedspace** [comment]
I just hacked the build.js file to pass all the test code through 6to5.transform() while building the HTML, then checked the results in IE10 (a platform known to pass only 3 tests natively, while passing all of ES5). The results I got were as follows:
- arrows
  - everything except "no line break..." and "no "prototype"..."
- const
  - everything except "is block-scoped" and "TDZ" for both strict and non-strict
- let
  - basic support (strict and non-strict)
  - for-loop iteration scope (strict and no-strict)
- defaults (all)
- rest
- spread (all)
- class
  - everything except "is block-scoped" and "extends" (the latter requires `__proto__`)
- super
  - everything except "in constructors" (because that requires `__proto__`)
- object literal extensions (all)
- octal and binary literals
  - everything except the Number() tests
- RegExp 'u' flag
- destructuring
  - everything except "destructuring defaults" and "defaults in parameters"
- Unicode escapes
- Symbol.iterator

(Also it spuriously passed some of the negative `__proto__` tests, but those are due to the tests' code not checking for basic functionality first - whoops.)

(Now, I know what you're thinking: how did it fail the let block-scoping test? Well, I suspect there's a [bug](https://github.com/6to5/6to5/issues/150) in the thing.)

**Comment by sebmck** [comment]
@webbedspace Any chance I can get the modified build source? Would love to iron out all 6to5 bugs.

**Comment by webbedspace** [comment]
I, er, plan to integrate it as a formal pullreq to this repo in the next day or two. (Specifically, as a command-line option to build.js.)

(Incidentally, I'm a little suspicious of that Symbol.iterator result... I'm pretty sure IE10 actually evaluated `Symbol.iterator` to `<td id="Symbol">.iterator`, a.k.a. `undefined`, and the for-of loop just happened to exploit that.)

**Comment by UltCombo** [comment]
Isn't `Symbol.iterator` polyfilled by `require("6to5/polyfill")`?

**Comment by sebmck** [comment]
@webbedspace 6to5 only transforms and worries about syntax. ES6 polyfills are up to the developer, 6to5 never tries to emulate an entire ES6 environment. Although the optional `require("6to5/polyfill");` does it rather well.

**Comment by webbedspace** [comment]
OK, you can try it out if you want: #309 (I've since found that a few tests' code was broken, so the above posted results are no longer firmly accurate).

**Comment by kangax** [comment]
I suppose I can close this now that @webbedspace added 6to5 results

**Comment by UltCombo** [comment]
Nice work, thanks @webbedspace !
