### ISSUE TITLE
Not counting 'let' in Firefox

### ISSUE THREAD

**Issue by evilpie** [compat-table/compat-table#288]
It seems like some recent changes now show Firefox as not supporting "let". On the other hand Chrome is shown as supporting "let" even though that requires setting a flag. I wager changing the script type= isn't very different from something like that.

**Comment by webbedspace** [comment]
There's a footnote attached to the Firefox result squares for two of the `let` subtests. This is similar to the footnote attached to `Array.prototype.values`, signifying it exists as the non-standard `Array.prototype["@@iterator"]`.

The reason Chrome currently gets a (false positive) pass is because its flag guards about 90% of its ES6 implementations, and footnoting that many results would be a little unreadable. (Though, eventually some sort of sigil denoting the `#enable-javascript-harmony` flag will have to be added to those results anyway - see #188).
