### ISSUE TITLE
display no for 0/x and yes for x/x results

### ISSUE THREAD

**Issue by michaelficarra** [compat-table/compat-table#293]
Showing "6/6" is less immediately clear than "Yes". Likewise, "0/6" is less clear than "No".

**Comment by webbedspace** [comment]
I can't speak for everyone, but I prefer "6/6", "3/3" etc. because I think it should be consistently obvious that the test is a collection of subtests - "Yes/No" currently consistently denotes that a single Javascript test snippet passed. 

Also, I think "Yes" as _only_ applying to 100% conformant results is, I feel, a bit misleading - the Symbols in, say, Chrome at present are very usable even though they fail String() conversion, so to imply it falls short of a "yes, it's supported" is, in that particular case, a bit of a presumption.

**Comment by kangax** [comment]
I'm inclined towards 6/6 as well.

@domenic @rwaldron @jdalton @toshok any preferences?

**Comment by jdalton** [comment]
Cc @bterlson

**Comment by bterlson** [comment]
+1 for 6/6. "Yes" & "No" is a judgment call that developers should make depending on the specific tests that pass or fail. 1/6 could be a "Yes" for you if you only care about very basic functionality. Conversely, a 6/6 could be a "No" depending on whether the tests accurately represent all the ways a developer wants to use a feature.
