### ISSUE TITLE
Update/add IE tech preview

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#306]
- https://twitter.com/jdalton/status/532632322919518208
- https://twitter.com/dstorey/status/532625543078760448

**Comment by webbedspace** [comment]
Let's see what we got here...
All of these require "Enable experimental web platform features" in `about:flags`, or it's just the same IE11 results.
- arrows
  - everything except "no line break"
- const (all)
- let
  - same results as IE11
- rest
- spread (all)
- class (all...!!)
- super (all)
- object literals (all)
- for..of
- octal/binary
  - everything except Number()
- template strings
  - basic functionality (FWIW, it fails the tagged test because it A) doesn't support .raw, and doesn't handle "\n" in templates correctly - removing it entirely.)
- block-level function declaration
- RegExp 'u'
- TypedArrays (all)
- Map/Set/WeakMap/WeakSet (all)
- Proxy
  - everything except "ownKeys"
- Reflect (all... but based on a few rough tests of Reflect.ownKeys, maybe functionality is lacking.)
- BLFD
- Promise
- Object static methods
  - all except Object.assign
- String static methods (all)
- String prototype methods
  - all except #contains 
- Unicode escapes
- Symbol
  - all except String()
- global symbol registry
- well-known symbols
  - Symbol.iterator
  - Symbol.unscopables
- Array static methods (all)
- Array prototype methods (all)
- Number properties (all)
- Math methods (all)
- Annex B:
  - same as IE11

**Comment by kangax** [comment]
Yep, looks about right!

**Comment by kangax** [comment]
...not to mention incredibly impressive

**Comment by webbedspace** [comment]
While recording these results I actually discovered a few bugs with the existing tests. These have been revised in #308, and the above results take those into account (for instance, IETP fails the current live super test, but only due to a bug in the test).

**Comment by dentuzhik** [comment]
I can make a PR on weekend.
And btw according to IE team the new Edge mode will be default in the next major version of IE.
http://blogs.msdn.com/b/ie/archive/2014/11/11/living-on-the-edge-our-next-step-in-interoperability.aspx
