### ISSUE TITLE
Add FF36 which is at 69% (from FF35's 59%)

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#324]

**Comment by webbedspace** [comment]
I think we should hold off on FF36 until it's entered Aurora phase, because it's likely that a number of its features may be "Nightly build only" and they may not have any hope of reaching the stable build yet. (Of course, Array#<s>contains</s>includes is listed in the ES7 table with a footnote, a practise I don't entirely agree with ATM.)

Anyway, the changes:
- const
  - passes all remaining tests
- octal/binary literals
  - passes all remaining tests
- WeakMap
  - constructor arguments
- Object static methods
  - getOwnPropertySymbols
- Symbol
  - all tests (NOTE: previous Nightlies also passed this, only to withdraw support in Aurora and higher.)
- global symbol registry
- well-known symbols
  - Symbol.iterator

**Comment by kangax** [comment]
Good to know, thanks @webbedspace

**Comment by diegobfernandez** [comment]
FF36 is now Aurora.
I think it should be added.
