### ISSUE TITLE
`class extends null` is invalid

### ISSUE THREAD

**Issue by sebmck** [compat-table/compat-table#380]
January 20, 2014 Draft Rev 22

> - extends clause of a class declaration is now a LeftHandSideExpression

14.5

> _ClassHeritage_ [Yield] :
> **extends** _LeftHandSideExpression_ [?Yield]

**Comment by webbedspace** [comment]
This feels like a spec mistake, considering the support `extends null` had in past TC39 notes - but besides that, I'm pretty sure that alone doesn't preclude this phrasing:

``` js
var foo = null;
class C extends foo {}
```

**Comment by sebmck** [comment]
``` javascript
var foo = null;
class C extends foo {}
```

is still supported.

See [these TC39 notes](https://github.com/rwaldron/tc39-notes/blob/c61f48cea5f2339a1ec65ca89827c8cff170779b/es6/2013-11/nov-19.md#classoptional-yield-arg-ambiguity) for where this was decided.

**Comment by jamiebuilds** [comment]
@domenic @wycats ping

**Comment by webbedspace** [comment]
I sought an expert opinion, and it turns out [null literals are a LeftHandSideExpression](https://twitter.com/webbedspace/status/550898215130640384).

(For those confused, most of the restrictions that are normally associated with LValues, such as preventing `2 = 4`, are enforced not by the grammar but by slews of early error conditions such as [these](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors) (in particular, those citing IsValidSimpleAssignmentTarget)).

**Comment by sebmck** [comment]
That can't be right. That's such bizzare and weird behaviour.

```javascript
$ node
> null = "wow";
ReferenceError: Invalid left-hand side in assignment
```

**Comment by sebmck** [comment]
That's so bizzare. Thanks for the clarification!

**Comment by domenic** [comment]
It's not a syntax error, but it's still a dynamic error (ReferenceError).
