### ISSUE TITLE
Test generic nature of for..of

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#494]
As per https://twitter.com/alexilyaev/status/585910096628064259

@webbedspace I believe we don't do this yet? There's iterable test but nothing NodeList-like (numeric indices, length, etc.)

**Comment by zloirock** [comment]
Because DOM iterable is not part of the ES6? :)

BTW, `core-js` adds default iterator to `NodeList`, but not to [`HTMLCollection`](https://github.com/zloirock/core-js/issues/37) - Chromium bug, fixed only in the latter.

**Comment by alexilyaev** [comment]
@zloirock I've tested with Chrome as is and with Babel, doesn't work in both.
As I understand, Babel comes with `core-js`, right?

**Comment by kangax** [comment]
> Because DOM iterable is not part of the ES6? :)

Of course. Hence "generic nature and NodeList-like", not "NodeList" ;) But I didn't check spec to see if MDN (that claims it should work) is right.

**Comment by zloirock** [comment]
@alexilyaev [yep](http://goo.gl/BlkFiM)

**Comment by alexilyaev** [comment]
Adding MDN ref:
[MDN - Iterating over DOM collections](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of#Iterating_over_DOM_collections)

**Comment by webbedspace** [comment]
NodeLists are only accessible by for-of in browsers because the browser's DOM is expanded to include `NodeList.prototype[Symbol.iterator]` - which is to say, NodeList instances are upgraded to generic iterables.
![](http://i.imgur.com/u3QV0yr.png)
No change necessary, as the generic iterables tests cover this behaviour. 

Note of clarification: Unlike `Array.from()`, the remaining iterator syntax (spread, square-bracket destructuring, for-of, `yield *` etc.) don't treat numeric indices and `length` as anything special.

Second note: the [WHATWG DOM Standard](https://dom.spec.whatwg.org/#old-style-collections:-nodelist-and-htmlcollection) gives the NodeList and DOMTokenList interfaces the `iterable` attribute, which is generally interpreted to mean "ES6 Symbol.iterator protocol".

**Comment by kangax** [comment]
Thanks @webbedspace

**Comment by kangax** [comment]
We can also consider having a separate place for tests like this — anything DOM related that has cross-over with ES6 (iterates on nodelists, subclassing of various interfaces (node, element, nodelist, etc.), configurability/freezability/etc., other well-known symbols (e.g. toString), etc.)

**Comment by alexilyaev** [comment]
@webbedspace Shouldn't this be added by `core-js`?
@kangax I'd love to see that added :-)

**Comment by zloirock** [comment]
@alexilyaev `core-js` adds `NodeList` default iterator as part of DOM spec, not ES6. See references from [this](https://github.com/babel/babel/issues/545#issuecomment-70861920) thread.
