### ISSUE TITLE
Add Safari 9 results

### ISSUE THREAD

**Issue by matiassingers** [compat-table/compat-table#556]
Update table with Safari 9 ES6 support.

![screen shot 2015-06-09 at 17 12 40](https://cloud.githubusercontent.com/assets/938453/8054369/c586e540-0eca-11e5-97ed-96f971ed499c.png)

See [Safari 9 release notes](https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html) for more details.

**Comment by ljharb** [comment]
We'll need to make sure this is tested in an actual copy of Safari 9 - can that only be obtained by installing the OS 10.11 beta as a primary OS?

**Comment by webbedspace** [comment]
We already know what's in Safari 9: it's another WebKit revision. We just need to know which particular revision, and I assure you the results will be the same. (Of course, checking the actual branded product wouldn't hurt, but don't expect anything out of the ordinary.)

On a personal note, I'm pleased they've given top billing to support for the `Number` constructor. :P (Yes, I know what they meant to type.)

**Comment by matiassingers** [comment]
Good point @webbedspace!

Doesn't seem like they are even shipping Safari 9 with the builds yet: 

> [![safari 8.1 info](https://pbs.twimg.com/media/CHDpeS3XIAAZ36E.png)](https://twitter.com/doney/status/608242656993492992)
> — [@doney](https://twitter.com/doney/status/608242656993492992)

**Comment by webbedspace** [comment]
No, the Safari X.1 version numbers are identical to the (X+1).0 numbers, but denote backwards-compatibility (see: 6.1 and 7.0, 7.1 and 8.0). Anyway, that number isn't immediately useful because WebKit build numbers are SVN changeset numbers (current being 185361) whereas Safari build numbers are different.

**Comment by ljharb** [comment]
See https://github.com/MicrosoftEdge/Status/pull/226#issuecomment-97672727 - being in WebKit does not mean something is necessarily in Safari.

**Comment by kangax** [comment]
> See MicrosoftEdge/Status#226 (comment) - being in WebKit does not mean something is necessarily in Safari.

That's news to me as well. Ok, we'll make sure to test explicitly then.

**Comment by silverwind** [comment]
Current Safari 9 beta (11601.1.37.1) gets 53% with miniscule differences to current WebKit (54%).

**Comment by mgol** [comment]
Is there anything blocking the addition of Safari 9 beta test results? Safari 9.0 (11601.1.50) gets 55% currently. I can upload the data if that's the only blocker. Unless the Apple EULA disallows it but Apple has talked about Safari 9 standards support publicly so I assume it should be OK...

**Comment by kangax** [comment]
@mzgol let's add it, could you please make a PR?

**Comment by mgol** [comment]
@kangax Sure. Is there any way to populate the results or do I have to copy them manually to data-es6.js?

**Comment by kangax** [comment]
@mzgol Manually. Automatic import would be an interesting option; I'm not sure exactly how it would work though — you'd click "export" while in a browser and it would generate what, diff?

**Comment by mgol** [comment]
> Automatic import would be an interesting option; I'm not sure exactly how it would work though — you'd click "export" while in a browser and it would generate what, diff?

I see it like that:
1. You'd click "export" in a browser and save the file as `browser-data.json`. You might be asked a few questions to be able to fill the browser definition (like the short/long name etc.).
2. You'd then run `node ./merge-data.js --to es6-data.js --from browser-data.json` and you'd get a modified `es6-data.js` with a new browser added. There would have to be a `merge-data.js` script that would be able perform that action.

Since it's manual for now I won't have time today but I'll try tomorrow if no one beats me to it. :)

**Comment by kangax** [comment]
Created https://github.com/kangax/compat-table/issues/614

**Comment by mgol** [comment]
PR: #616
