### ISSUE TITLE
Bad results for "current browser" with Firefox nightly?

### ISSUE THREAD

**Issue by laurentj** [compat-table/compat-table#578]
I go [on the compatibility table](http://kangax.github.io/compat-table/es6/) with the latest Firefox nightly. During the table construction, I see 16/23 for classes, 6/7 for super, 20/22 for generators (and probably for other features) in the column "current browser". But when the table is constructed, the score goes down respectively to 2/23, 0/7 and 17/22. (whereas classes seems to be partially implemented for example..).

Why this change?

**Comment by webbedspace** [comment]
The table does not list "Nightly only" features - Firefox's class support is currently restricted to Nightly builds only. Also, the class support currently requires that a `constructor` always be supplied, which causes it to fail all but 2 of the tests. (Since I expect this to be fixed before the class support is propagated to end-user Firefox builds, I won't modify the tests to accommodate it.)

Furthermore, the "current browser" column is only calculated after the page has finished rendering, by dynamically running the test code.
