### ISSUE TITLE
Lots of "%TypedArray%[object Object]" tests

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#644]
Under "typed arrays" there are lots of tests named "%TypedArray%[object Object]", they all seem to be broken.

**Comment by zloirock** [comment]
Thanks.

Regression in:
https://github.com/kangax/compat-table/commit/1ab5b86d556ad925b792e9ceede4c5966bdeab8b (@webbedspace) - missed property name.
https://github.com/kangax/compat-table/commit/afa89886cdf8a954f5572b3c96f50122582c9a08 (@ljharb) - usage `Function` instead of `eval` breaks [multi-line comments hack](https://github.com/kangax/compat-table/blob/gh-pages/build.js#L684).
https://github.com/kangax/compat-table/commit/60139ea9d160aeb505a2a7906bd6c4a5589d447b (@ljharb) - missed bracket + `return false` in `.forEach` callback.

Please, fix me if I'm wrong anywhere.
