### ISSUE TITLE
Compatibility table is unusable in Safari

### ISSUE THREAD

**Issue by loganb** [compat-table/compat-table#645]
The compatibility table is unusably slow in Safari (both 8 and 9). Redraw is so slow, that the page is effectively unusable and cannot be scrolled and having the window in the foreground pegs a CPU.

**Comment by kangax** [comment]
Sorry about that. I'll be looking into optimizing it hopefully this weekend!

**Comment by loganb** [comment]
Thanks! Great table though. Very helpful. :)

**Comment by kangax** [comment]
Thank you, that's the goal ;)

**Comment by ljharb** [comment]
I've noticed the same but haven't had a chance to look into it - I look forward to @kangax's optimizations :-)

**Comment by claudepache** [comment]
I've already noticed and analysed that some time ago. The problem occurs when using `overflow: auto` instead of the default `overflow: visible` on a element containing many stuff. The `overflow: auto` was added in b568330 by @williamboman. I had a brief discussion with him on williamboman/compat-table@1e21e701bc19f2c154ff37eb3ab93e6955c54b57 and the conclusion was that it is needed for the responsive design (in its current form).

**Comment by ljharb** [comment]
It's worth noting that "responsive" isn't more important than "works in all the major browsers".

**Comment by kangax** [comment]
Thanks for the research, Claude!

I'll see if I can find a solution that keeps responsive without sacrificing
performance but in the worst case scenario, I'd prefer performance over
responsiveness (considering that it's practically impossible to use it
otherwise).
