### ISSUE TITLE
Point system seems subjective

### ISSUE THREAD

**Issue by jacksonrayhamilton** [compat-table/compat-table#687]
The compatibility table assigns features point values; "Minor difference (1 point)", "Landmark feature (8 points)" etc. But these ratings seem subjective. What makes a feature more or less significant?

e.g., Promises, while useful, were already informally standardized and implemented in ES5. In my opinion that makes the feature less significant; yet it's labelled "landmark". Whereas tail calls are merely "significant" (apparently less ground-breaking than syntactic sugar like spread and computed object literal keys), even though tail calls enable new algorithms and programming styles.

I'm not trying to convince you to re-rate these particular features. I'm pointing out that "significance" is a matter of opinion. Ratings aren't facts, which makes them seem out-of-place in a table of statistics.

Rating the features doesn't seem to have anything to do with compatibility, unless the rating has some correlation to the probable difficulty of implementation. I suggest removing these ratings.

**Comment by ljharb** [comment]
Promises were not in ES5 whatsoever - they were informally standardized as Promises/A+, but not until ES6 were they part of the language. It's landmark because it's a critical language primitive - being able to implement it with ES5 methods doesn't reduce its important in any way.

Of course significance is a matter of opinion - but I'm not sure why one would expect there to be no opinions whatsoever just because it's in a table. The significance is used to weight completion percentages. You're free to ignore it and simply look at the individual features you care about.

**Comment by zloirock** [comment]
> It's landmark because it's a critical language primitive

`Map` and `WeakMap` definitely critical language primitive, but marked as `significance: 'small'`, `Symbol` marked as `medium`. Makes sense to reconsider some positions.

**Comment by ljharb** [comment]
That's fair. This issue seems to be to remove the significance entirely - we should open a new one to discuss specific modifications,

**Comment by jacksonrayhamilton** [comment]
@ljharb:

> Promises were not in ES5 whatsoever

To clarify, I meant that it was possible to implement promises using ES5. The only difference between then and now is potentially one less dependency.

> The significance is used to weight completion percentages.

I see. In that case, I question the use of this statistic as a weight for "completion," again on the grounds of subjectivity.

**Comment by ljharb** [comment]
Even the feature list itself requires subjectivity, unless we're counting sections of the spec - which wouldn't be very useful. There's simply no way to be unbiased here.

**Comment by webbedspace** [comment]
To address one specific case: The reason WeakMap is marked `small` is because it's the same "type" of feature as WeakSet, which is also `small` – and `small` (0.25) + `small` (0.25) = `medium` (0.5).

I'm willing to increase proper tail calls to `large` – that particular feature can slide either way.

**Comment by jacksonrayhamilton** [comment]
Perhaps the choice of words was poor. "Minor," "useful," "significant" and "landmark" sound like words that denote one programmer's personal preference towards a feature. It seems like what you actually meant to describe was "the size of the feature relative to the total completion of the specification."

If so, you might consider a different presentation and a reevaluation of the feature set on that scale. Or (probably better) remove the "% complete" feature, as it seems to be too difficult / impossible to calculate (and not really all that useful anyway).

**Comment by ljharb** [comment]
It's quite useful - implementors (ie, browser developers) constantly use those numbers to gauge their progress in implementing the spec. It's long been an accepted and welcomed metric amongst core contributors of all of the major browsers.

**Comment by jacksonrayhamilton** [comment]
Except, as we've uncovered here, those numbers are likely inaccurate. The metric should be appreciated because it's meaningful; but I doubt it is.

The usefulness of a percentage to implementors hinges on the supposition that implementing the entire spec is worth encouraging, which is also debatable. From my perspective, and I have the best intentions for implementors and programmers alike, we'd be much _better_ off with many of these features out of the hands of developers for as long as possible.

The metric is also overly-specific. 100% means the platform interoperates. 100% compliance, at least, could be calculated more fairly than anything else. Any number less than 100% means an implementor or user needs to consult the column for the features missing. If anything, a boolean value, "complete" or "incomplete" could be fairly accurate while also useful.

**Comment by ljharb** [comment]
There's no "accuracy" to aim for. They're simply an arbitrary number that rises as implementors implement things. It's useful to progress from 0 to 100 simply to _measure progress_ and make people _feel good about it_. In addition, it's a completely negative and useless attitude to wish for these features to be delayed, and all of them are being implemented in all of the browsers at a breakneck speed. All future specs will only include things that 2 browsers already ship.

No engine is 100% compliant, even with ES5 (the table is missing a number of bugs). The goal isn't "100% or nothing" - it's not binary.

**Comment by jacksonrayhamilton** [comment]
I'm trying to provide some perspective. Our ideas of what constitute "progress" and "usefulness" are probably irreconcilable. By doubling this table into a game for implementors, you've injected personal philosophy into it. I urge you to purify these statistics. Assert the "goodness" and/or "size" of the features elsewhere.

**Comment by webbedspace** [comment]
If you want me to replace the words "useful" "significant" and "landmark" with less loaded terms (maybe just "tiny", "small", "medium", and "large", which are basically semantically vacuous for objects like "features"), I can do that too.

> The usefulness of a percentage to implementors hinges on the supposition that implementing the entire spec is worth encouraging, which is also debatable. 

Well… there have already been situations in JS's history where deviating from the then-current spec was worthwhile – one noteworthy case being the duplicate property name restriction in object literals in ES5, which implementors need to remove to implement ES6. In the event that it turns out that a certain ES6 feature should not be developed, then such a reversal would surely end up in a future specification, such as ES7 or ES8. The platforms adhering to this would no longer have 100% for ES6, but would be in the running to get close to 100% for ES7, which would be regarded as a more worthwhile goal. So, the table's scores only put worth on "100% of ES6 implemented" insofar as the concept of "implementing ES6" has cultural cachet.

**Comment by ljharb** [comment]
@jacksonrayhamilton there's nothing wrong with injecting personal philosophy into things, and things aren't "more pure" without personal philosophy. If you disagree with a thing's personal philosophy, you're free to click "fork" and make your own variant.

**Comment by bterlson** [comment]
> It's quite useful - implementors (ie, browser developers) constantly use those numbers to gauge their progress in implementing the spec. It's long been an accepted and welcomed metric amongst core contributors of all of the major browsers.

Speaking for myself, the score is arbitrary and I don't quite agree with some of the classifications. And then when you start talking about things like "Strict mode only implementations get 20% credit" and it starts getting more arbitrary. This implementer cares less about the scoring algorithm than having a nice 3,048 meter view of the ecosystem. 

The goal should be to represent a number that most developers can identify with. This is a _hard problem_ so I think the current attempt seems overall reasonable (if somewhat arbitrary).

**Comment by ljharb** [comment]
Agreed on all points!

**Comment by kangax** [comment]
Folks, let's not jump into hasty conclusions with "you're free to click "fork" and make your own variant" :)

We all want compat table to be a useful and fair resource, so @jacksonrayhamilton, thanks for bringing this up. Unfortunately, as @bterlson and others mention, fairness is difficult. We can't make table entirely objective because there's no way to objectively group tests under feature "groups".

In a case of an official ECMA262 test suite, for example, you could simply show a result like 112/956 — number of passing tests vs. number of total tests. But in our case, we'd like to give a more user-friendly overview; and that obviously comes with subjective decisions.

As for personal philosophy — historically, it played a huge role in moving standards forward. Remember Acid 2 test from 2005? It was a _subjective_ set of tests against various technologies/standards (html, svg, etc.); if you got a pretty smiley face, your browser passed. Browser vendors went crazy to comply. Lo and behold, we had things from acid tests being added and/or fixed in all of the main browsers. Things like this might seem silly (and could certainly be taken overboard) but they matter and they work. It's likely that current ES6 progress wouldn't be as fast and extensive if not for a subjective resource like a compat table. 

We try to follow some sort of common sense but are always happy to hear suggestions for improvement. If many people agree that certain features should be given higher score, let's hear it.

**Comment by jacksonrayhamilton** [comment]
Since providing a completion percentage is a goal, I think a better way to go about it would be what @webbedspace suggests: Use the words "tiny," "small," "medium," and "large," to denote the relative size of a feature (as in, a guess for the time and effort it will usually take to implement it).

For instance, the impression I got from SICP was that tail calls were possible thanks to a clever yet simple compiler optimization. I don't know if it's as easy in JS, but if it is, that'd be a "tiny" feature.

**Comment by bterlson** [comment]
Off topic, but tail calls are not simple to implement for JS VMs. If we had the luxury of not thinking about arguments.caller, error.stack, and other such "edge cases" it might approach "simple", but even then it's quite a bit of work if you don't want tail calls to result in performance degradation.

**Comment by jacksonrayhamilton** [comment]
Looks like [the wording has been changed](https://github.com/kangax/compat-table/commit/6041f0f1ab95e8e9107955c69e3884cb7f32afd1#diff-74851a955d28cd20218dd75997da85a4L112), thanks for addressing this.
