### ISSUE TITLE
String trimming is stage 1, not stage 3 (candidate)

### ISSUE THREAD

**Issue by rauschma** [compat-table/compat-table#695]
- String trimming: https://github.com/sebmarkbage/ecmascript-string-left-right-trim
- Listed as stage 1 here: https://github.com/tc39/ecma262#current-proposals

**Comment by zloirock** [comment]
https://github.com/kangax/compat-table/commit/2f48abc4a1fb6a5e39cefe7edb9467385144cc34 , but in the meeting notes [also stage 1](https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-29.md#612-spec-defacto-stringprototypetrimlefttrimright).

@sebmarkbage @ljharb ?

**Comment by ljharb** [comment]
Hmm - I did that during the meeting so I'm pretty confident that since all browsers ship it, it was agreed to be at stage 3. However, since the meeting notes and the ecma262 repo don't agree, we should probably drop it to stage 1.

The next meeting is this week, however, so I'll bring it up and confirm then.

**Comment by rauschma** [comment]
By what you are saying, stage 3 sounds likely, though. The ecma262 repo may simply not be up to date, yet.

**Comment by sebmarkbage** [comment]
It needs a review for Stage 3. Could've been Stage 2 but I didn't bother with that since we'll jump to Stage 3 when the homework is don't.

**Comment by ljharb** [comment]
Then 2f48abc4a1fb6a5e39cefe7edb9467385144cc34 was my misunderstanding/mistake, and we should drop it to stage 1.
