### ISSUE TITLE
Freeze table header if we scroll down table

### ISSUE THREAD

**Issue by greybax** [compat-table/compat-table#715]
Now it looks like:
![compat1](https://cloud.githubusercontent.com/assets/3235047/12018092/ebcc177c-ad6f-11e5-8a2b-89bcc7e3a387.png)

and if we scroll down table that we couldn't see which column matches to which browser:
![compat2](https://cloud.githubusercontent.com/assets/3235047/12018122/48f87bf2-ad70-11e5-8d00-88a9e6f79438.png)

I'd like to propose to freeze table header while scrolling the table, so this UI will be more understandable:
![compat_good](https://cloud.githubusercontent.com/assets/3235047/12018167/d4945208-ad70-11e5-9b69-d2deba1ee040.png)

**Comment by webbedspace** [comment]
For some history on the sticky header issue, see #120 and #532.

**Comment by kangax** [comment]
I looked at https://github.com/filamentgroup/fixed-sticky but it doesn't support fixed table headers. I also tried using http://philipwalton.github.io/polyfill/demos/position-sticky/ and it doesn't seem to work either.

**Comment by kangax** [comment]
Some sort of success with floatThead plugin but not entirely. For tracking, the issue is here — https://github.com/mkoryak/floatThead/issues/276

**Comment by kangax** [comment]
Phew, this is now fixed. Check it out.

**Comment by greybax** [comment]
:+1: :smiley: :santa: :tada:

**Comment by zloirock** [comment]
![default](https://cloud.githubusercontent.com/assets/2213682/12053686/a566a3d8-af45-11e5-965f-83dfd3dd1369.png)
Non-standard, ES5 tables, FF, IE.

**Comment by mkoryak** [comment]
ill take a look later today

this looks like a real bug! i

**Comment by mkoryak** [comment]
I have a fix, just need a bit more time to add in all the other fixes I proposed to the pr

**Comment by mkoryak** [comment]
https://github.com/kangax/compat-table/pull/718

I blame FF for that bug, for some reason it was reporting the table width incorrectly (bigger by about 40px) because it wasnt actually taking up 100%, changing from `width` to `min-width` fixed it. 

im going to spend a bit more time looking at the performance of the plugin when enabling sorting. Its weird that its slower than when disabling it (on FF). Maybe its just because I have 4% power.

**Comment by mkoryak** [comment]
by the way, this plugin does not play with mobile. making the browser reflow tables is not nice and safari especially does not like it. 
your giant table probably also doesnt work on mobile, so this might not be a concern.

**Comment by BillyWM** [comment]
@mkoryak Using min-width for tables is undefined behavior and should not be relied upon. There are two table-layout algorithms*, auto and fixed, and when using fixed (as this table is) the width is determined by the widths explicitly defined in CSS

https://www.w3.org/TR/CSS21/visudet.html#min-max-widths

> In CSS 2.1, the effect of 'min-width' and 'max-width' on tables, inline tables, table cells, table columns, and column groups is undefined.

Separately, you may be having an issue with grabbing the width via Javascript. Using "box-sizing: border-box" changes how the width of a particular cell is calculated: padding becomes internal to the cell, a part of the width. If you use jquery's .width() you may not get the value of a cell using this box-sizing method accurately reported, vs using other methods:

Example:

The inspector says the TH with class "test-name" has width 349.3 and padding 5.85. Thus the right width value is 361, as 5.85 \* 2 + 349.3 = 361.

> $(".test-name").width()
> 349.3
> 
> getComputedStyle(document.querySelector(".test-name")).width
> "361px"

---

From the JQuery docs:

http://api.jquery.com/width/

> Note that .width() will always return the content width, regardless of the value of the CSS box-sizing property. As of jQuery 1.8, this may require retrieving the CSS width plus box-sizing property and then subtracting any potential border and padding on each element when the element has box-sizing: border-box. To avoid this penalty, use .css( "width" ) rather than .width().

---
- two and a half algorithms if you count IE playing by slightly different rules per usual https://connect.microsoft.com/IE/feedback/details/781009/ie-10-fails-to-render-tables-width-fixed-layout-correctly

**Comment by mkoryak** [comment]
Wait,  I'm having a problem? I don't use jquery width to measure cell widths. 
Also I have to set min width in case the table who's thead I removed becomes less wide because it's widest cells were in the thead. I would have been happier if I didn't need to touch it at all,  but it is needed for that case. 

Do you see a layout issue or is your comment just general info?

**Comment by mkoryak** [comment]
Also the behavior here is far from undefined.  It fixed a bug.  If you want to do it with out using min width, please be my guest ;)

**Comment by BillyWM** [comment]
The comment was in reference to incorrect computed values being reported and applying min-width.

> I blame FF for that bug, for some reason it was reporting the table width incorrectly (bigger by about 40px) because it wasnt actually taking up 100%, changing from width to min-width fixed it.

I've spent significant time learning the ins and outs of taming dynamically generated tables across devices. Speaking from experience, if the markup is well-behaved, then the only browser that should still cause you pain is IE, not the evergreen browsers. The application of min-width to a fixed table layout hints at an underlying markup issue. As for runtime calculation of sizes with Javascript, when I've had similar issues it has turned out to be a failure to consider all factors that contribute to the size of the element rather than an underlying browser bug (But if there is a bona fide computation bug in Firefox I'd be interested to know so that I don't fall victim to it myself)

As for undefined behavior, referring back to the quote from before, the standard explicitly states that "the effect [....] is undefined". Firefox can honor the property and other browsers can ignore it, and both are valid. This is unreliable. Some de-facto standards become formal standards (XMLHttpRequest), but at this time no specific behavior for min-width applied to tables is part of the formal standard.

See the line "Applies to table": https://developer.mozilla.org/en-US/docs/Web/CSS/min-width

If these data are accurate then only Firefox and Opera honor min-width. Personally I avoid the trouble and instead prefer to judiciously apply width values to elements and their wrappers such that a fixed-layout table renders consistently.

Just my $0.02, FWIW, as I'm familiar with the topic. If there continue to be layout issues I wouldn't mind submitting a PR to help, but I'd be more interested in fleshing out any missing data and submitting additional tests.

**Comment by chicoxyzzy** [comment]
Issue mentioned in header is resolved. Bug from https://github.com/kangax/compat-table/issues/715#issuecomment-168031122 may be tracked here #967

**Comment by zloirock** [comment]
Nope.
![image](https://cloud.githubusercontent.com/assets/2213682/20523479/15e4a7ae-b0ad-11e6-8dfe-21694533627f.png)

**Comment by zloirock** [comment]
Oops, I have read only the first part of your comment, sorry :-) However, I think that it's the same issue.
