### ISSUE TITLE
Property enumeration order inaccurate

### ISSUE THREAD

**Issue by nzakas** [compat-table/compat-table#721]
The current property enumeration tests for `for-in` and `Object.keys()` suggest that there is a specific ordering they should follow. However, the only thing required by the spec is that `for-in` and `Object.keys()` return the same order rather than some previously-defined order.

Perhaps the two tests should be combined?

References:

> If an implementation defines a specific order of enumeration for the for-in statement, the same order must be used for the elements of the array returned in step 4.

Source: http://www.ecma-international.org/ecma-262/6.0/#sec-object.keys

> Historically, the for-in order was not defined and there has been variation among browser implementations in the order they produce.(and other specifics). ES5 added Object.keys and the requirement that it should order the keys identically to for-in. During development of both ES5 and ES6 the possibility of defining a defining a specific for-in order was considered but not adopted because of web legacy compatibility concerns and uncertainly about the willingness of browsers to make changes in the ordering they currently produce.

Source: https://esdiscuss.org/topic/property-ordering-of-enumerate-getownpropertynames

**Comment by nzakas** [comment]
Related: https://github.com/nzakas/understandinges6/issues/206

**Comment by webbedspace** [comment]
My interpretation of the spec was that `Object.keys` uses the order of [EnumerableOwnNames](http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames), which obtains the list from [OwnPropertyKeys](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys)… however, it seems I hadn't noticed that step 6 of EnumerableOwnNames alters the ordering of OwnPropertyKeys's list. OK, the issue is noted.

**Comment by ljharb** [comment]
I agree - only new methods in ES6 follow the defined iteration order, for backwards compatibility, existing methods should follow for..in order.

**Comment by raulsebastianmihaila** [comment]
Actually getOwnPropertyNames guarantees the order of the keys: http://www.ecma-international.org/ecma-262/6.0/#sec-object.getownpropertynames
