### ISSUE TITLE
Move most stuff out of ES2016 (called ES7 here)

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#734]
ES7 will contain only 2 new features, the rest should be moved to ES.next or sth like that. Source: http://www.2ality.com/2016/01/ecmascript-2016.html

Also, perhaps the naming should be aligned with the spec? ES6 was a widely recognized name because ES2015 was coined when ES6 & ES7 were already in use. With the yearly ECMAScript releases going further with calling new versions ES8, 9, 10 etc. will start getting confusing.

**Comment by ljharb** [comment]
1) I strongly agree we need an "ES Next" table which contains all non-stage-4, but only stage-0 and above, proposals.
2) I think both names - ES6/ES2015, ES7/2016 are widely accepted. Going forward, perhaps ES2017 (the 8th edition of ES) will be the first one solely known by its year instead of its edition number. I don't think the compat tables need to make a real choice here just yet.

**Comment by kangax** [comment]
1) ES next — yes, of course, we should totally add it (and move all the remaining stuff)
2) I really dislike ES20xx notation and I think it was a mistake to introduce year-based labels in the first place. ESx was already highly recognized so it only added more confusion, more cognitive overload, and didn't add any benefit. That's why I stuck to the gun... eh, original labels. Unless it becomes a real problem, I'd like to keep them short and... old school.

**Comment by zloirock** [comment]
My point of view - too early split `ES7` and `ES next`. Better replace `ES7` to `ES7+` in templates :) And I also hate ES20xx notation :)

**Comment by ljharb** [comment]
It's not too early - anything not in ES7 as of last week simply will not be in it.

I'm on board with avoiding the year notation :-) However, it might be better to just have an "ES Next" page, with stages, and once stage 4 things get published in a year, they could be bumped up to a higher section labeled with the year/edition number?

**Comment by zloirock** [comment]
@ljharb I know it. Too many features were changed in ES6 after freeze adding new features.

**Comment by ljharb** [comment]
ES6 was a very different process than ES7 and everything after it.

**Comment by ljharb** [comment]
More specifically, none of the proposals that aren't already stage 4 will be in ES7/ES2016 - there might be a few more errata but none are currently represented on the ES7 table.

**Comment by zloirock** [comment]
> However, it might be better to just have an "ES Next" page, with stages, and once stage 4 things get published in a year, they could be bumped up to a higher section labeled with the year/edition number?

It makes sense.
