### ISSUE TITLE
Add Servo

### ISSUE THREAD

**Issue by yukulele** [compat-table/compat-table#831]
Add Servo, the new Mozilla browser engine
https://servo.org/

**Comment by chicoxyzzy** [comment]
Servo is not ECMAScript engine. It's render engine

**Comment by chicoxyzzy** [comment]
Closing this as unrelated to this compatibility table

**Comment by jugglinmike** [comment]
Could we revisit this feature request? It's true that the Servo project does
not itself implement an ECMAScript engine, but it does include
one--SpiderMonkey. This is analogous for the V8 engine: both Chrome and Node.js
are listed in the table because, although they both embed the same engine, the
details of embedding can have observable effects on the runtime behavior.
Likewise, Firefox's presence in the table does not fully account for Servo.

**Comment by ljharb** [comment]
That's a fair point. @jugglinmike, would you be willing to PR in servo's results?

**Comment by chicoxyzzy** [comment]
Servo 0.0.1-8c58736989 is the latest version and AFAIK SpiderMonkey could be updated any time in patch (commit hash). Do we really want to support such unstable browser?

**Comment by ljharb** [comment]
Ah, I hadn't realized that Servo wasn't released yet.

Stability imo does not come into it (versions don't convey stability), but unless there's a non-nightly, actually released Servo, I don't think the table should add it yet.

**Comment by chicoxyzzy** [comment]
There are only nightlies for now

**Comment by jugglinmike** [comment]
This all seems reasonable to me. Documenting the feature request as "acceptable pending stability" is an improvement (however slight) over "won't fix."

**Comment by jugglinmike** [comment]
@yukulele was this feature implemented?

**Comment by yukulele** [comment]
no, but servo usage share is negligible

**Comment by jugglinmike** [comment]
I agree, though that's been true since this issue was opened. There are other reasons to value the performance of Servo. I've opened gh-1341 to make it clear that this is still desirable.
