### ISSUE TITLE
Should Node 5 be marked as obsolete?

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#866]
Because it's lifetime ended according to https://github.com/nodejs/LTS

**Comment by zloirock** [comment]
It should be marked as obsolete only at LTS end.

**Comment by ljharb** [comment]
Node 5 never entered LTS, so actually yes, as soon as v6 came out, v5 should have been marked obsolete. The same will apply to node 7 - when node 8 comes out, node 7 is instantly obsolete.

However, node 4 remains NOT obsolete, since it's still LTS, until April 2018, and v6 won't be obsolete until April 2019.

**Comment by chicoxyzzy** [comment]
@ljharb yes I know about Node 4. OK. I'll add PR soon if nobody else will take it
