### ISSUE TITLE
Should the index.html files be part of the repository?

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#898]
All the index.html files are automatically generated, so they don't need to be tracked in the repository.  
Currently most of the conflicts I get on my PRs are on the index.html files, so removing them would save this work for everybody.

**Comment by ljharb** [comment]
If they're not in the repository, they won't be on the website, since the repository's only branch is `gh-pages`.

We could work around that by having a `master` branch, but then we have to build all the tooling around keeping `gh-pages` up to date.

Requiring that contributors do `git checkout origin/master *.html` or something similar seems worth it.

**Comment by zloirock** [comment]
Something like that will cause too many problems. I think the best option - generate HTML on clients, but it also has many problems.
